### ISSUE TITLE
First release of Ultet

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/ultet#23]
Release the first version for POC purposes

```[tasklist]
### Tasks
- [ ] #13
- [ ] https://github.com/AbsaOSS/ultet/issues/25
- [ ] https://github.com/AbsaOSS/ultet/issues/36
- [ ] https://github.com/AbsaOSS/ultet/issues/28
- [ ] https://github.com/AbsaOSS/ultet/issues/29
- [ ] E2E testing
```

**Comment by benedeki** [comment]
Closing as there is a milestone for it now.
